Adapt to coq/coq#17836 (sort poly)
mit-plv/rewriter pull request #109
Opened 2023-09-18 11:03 UTC by SkySkimmer

2023-09-18 14:05 UTC, JasonGross requested changes

2023-09-18 14:05 UTC, JasonGross commented on src/Rewriter/Util/Tactics2/Constr.v
> +    | Proj _p _r c => f n c
Please version this file a la
https://github.com/mit-plv/rewriter/blob/26f5c8497a1e513b34ea65bcc6ec3b15b1b3d5a2/Makefile.local.common#L60
so that the change is backwards compatible.

2023-09-18 14:05 UTC, JasonGross commented on src/Rewriter/Util/Tactics2/Proj.v
> +  := Proj.equal x y.
Please version this file a la
https://github.com/mit-plv/rewriter/blob/26f5c8497a1e513b34ea65bcc6ec3b15b1b3d5a2/Makefile.local.common#L60
so that the change is backwards compatible.

2023-09-18 14:14 UTC, SkySkimmer commented
That's a lot of work for the overlay writer dealing with a build system I'm not familiar with. Can you do it yourself?

2023-09-18 15:13 UTC, JasonGross commented
Sure, what's the timeline on getting the PR merged?  It'll probably take me a couple days at least to find time.

2023-09-18 16:24 UTC, SkySkimmer commented
Probably not this week, I haven't finished the overlays and the doc, and then we will need reviewing and perf discussion etc

2023-09-19 15:30 UTC, SkySkimmer commented on src/Rewriter/Util/plugins/inductive_from_elim.ml.v819
it doesn't pick use this file for some reason, instead it uses the v818 one

2023-09-19 16:08 UTC, JasonGross commented on src/Rewriter/Util/Tactics2/Constr.v
> +    | Proj _p _r c => f n c
@SkySkimmer Could `iter_with_binders` be exposed in Ltac2 in Coq upstream?  Then we could just drop this definition in new versions of the file.

2023-09-19 16:17 UTC, JasonGross commented on src/Rewriter/Util/plugins/inductive_from_elim.ml.v819
I'm on it, give me a bit and I'll split off the PR that adds a v819 suite of files

2023-09-19 16:30 UTC, JasonGross commented on src/Rewriter/Util/Tactics2/Constr.v
> +    | Proj _p _r c => f n c
(`iter_with_full_binders` and `iter` would also be nice)

2023-09-19 16:42 UTC, JasonGross commented on src/Rewriter/Util/plugins/inductive_from_elim.ml.v819
https://github.com/mit-plv/rewriter/pull/112 for the v819 files, about to go add versioning for the three relevant files in Tactics2

2023-09-19 17:03 UTC, JasonGross commented on src/Rewriter/Language/Reify.v
> +      | Constr.Unsafe.Proj _ _ _
I've fixed this in #110

2023-09-19 17:04 UTC, JasonGross commented on src/Rewriter/Rewriter/Reify.v
> +                      | Constr.Unsafe.Proj _p _r c => aux c
I've fixed this in #111

2023-09-19 17:37 UTC, JasonGross commented
I hope #113 will pass CI and auto-merge in about 10--20 minutes.  #114 will take care of `Proj.v`, which is already compatible.  If you rebase this PR on top of that one, the changes should be pretty minimal (just the two v819 Tactics2 files).  Though if the constr iter functions can be upstreamed in Coq, that'd be even better

2023-09-22 12:56 UTC, JasonGross commented on src/Rewriter/Util/Tactics2/Constr.v.v818
> +    | Proj _p _r c => f n c
Sort poly isn't making it into 8.18, right?
```suggestion
    | Proj _p c => f n c
```

2023-09-22 12:56 UTC, JasonGross commented on src/Rewriter/Util/Tactics2/DestProj.v.v818
> +  | Proj p r v => (p, r, v)
```suggestion
  | Proj p v => (p, v)
```

2023-09-22 12:56 UTC, JasonGross commented on src/Rewriter/Util/Tactics2/Proj.v.v816
> +  := Proj.equal x y.
This change has already been done for 8.19, this is the 8.16 file
```suggestion
  := let dummy := make (Rel (-1)) in
     Constr.equal (make (Proj x dummy)) (make (Proj y dummy)).
```

2023-09-22 13:34 UTC, JasonGross approved these changes
LGTM, happy to merge once the Coq PR lands and CI here passes

2023-11-06 20:48 UTC, ppedrot commented
Please merge now.

2023-11-06 23:32 UTC, merged