Adapting to Coq PR #14711: Evd.check_univ_decl returns also the universe binders
mit-plv/rewriter pull request #30
Opened 2021-09-10 11:02 UTC by herbelin

`Evd.check_univ_decl` now returns also the universe binders by default. We seize the opportunity to propagate them when there are some.

To be merged synchronously with coq/coq#14711. Thanks in advance.

2021-09-10 15:28 UTC, JasonGross commented
Is this going to make it into the v8.14 branch?  If not, we should split off new compat files

2021-09-10 15:33 UTC, herbelin commented
It's a priori for 8.15. I'll create a 8.15 file then, if that's the procedure.

2021-09-10 15:40 UTC, JasonGross commented
It's a bit more complicated than that, since the Makefile also needs to be modified.  If you have trouble figuring out how to do it, I'm happy to make the split myself (probably later today).

2021-09-10 15:43 UTC, JasonGross commented
The commit that did this for 8.14 is at https://github.com/mit-plv/rewriter/commit/4e0ebab0abf93732998055dd05ffaf80b26a1d8d ; if you're down to make a separate PR that copies all the v814 files to v815 files and makes the corresponding changes in the Makefile, I'd be happy to merge it; otherwise I'll do it myself shortly

2021-09-10 15:56 UTC, herbelin commented
Then, that is probably safer if you do it. Thanks.

2021-09-10 19:51 UTC, JasonGross commented
Created as https://github.com/mit-plv/rewriter/pull/31, I'll merge that once the CI passes

2021-09-11 04:12 UTC, JasonGross commented
#31 merged, could you rebase this on current master and edit the .v815 file instead of the .v814 one?

2021-09-13 18:59 UTC, JasonGross requested changes
Note that this is still changing the .v814 file, and it should change the .v815 file, now

2021-09-13 19:09 UTC, herbelin commented
I pushed, hoping I made it right. Thanks.

2021-09-20 08:39 UTC, SkySkimmer commented
Please merge now

2021-09-21 13:13 UTC, SkySkimmer commented
@JasonGross ping

2021-09-21 15:39 UTC, merged